# exported from PySB model 'model_0'

import numpy as np
from pysb.integrate import Solver
import pylab as pl
import matplotlib.pyplot as plt
from pysb import Model, Monomer, Parameter, Expression, Compartment, Rule, Observable, Initial, MatchOnce, Annotation, ANY, WILD

Model()

# Default kinetic parameters
KF = 1e-6
KR = 1e-3
KC = 1

# linear proportion to the experimental data (fluorescence i think :S)
IC = 10000
lp = 1000

Monomer('RAF', ['state', 'MEK'], {'state': ['I', 'A']})
Monomer('TGFa', ['EGFR'])
Monomer('IGF1R', ['state', 'IGF1'], {'state': ['A', 'I']})
Monomer('IGF1', ['IGF1R'])
Monomer('PI3K', ['state', 'AKT'], {'state': ['I', 'A']})
Monomer('p70S6K', ['AKT', 'p1_site', 'ERK'], {'p1_site': ['u', 'p']})
Monomer('EGFR', ['state', 'TGFa'], {'state': ['A', 'I']})
Monomer('IRS1', ['AKT', 'p1_site', 'ERK'], {'p1_site': ['u', 'p']})
Monomer('MEK', ['RAF', 'p1_site', 'ERK'], {'p1_site': ['u', 'p']})
Monomer('AKT', ['p1_site', 'p70S6K', 'IRS1', 'PI3K', 'GSK3'], {'p1_site': ['p', 'u']})
Monomer('GSK3', ['AKT', 'p1_site', 'ERK'], {'p1_site': ['u', 'p']})
Monomer('ERK', ['p1_site', 'p70S6K', 'IRS1', 'GSK3', 'MEK'], {'p1_site': ['p', 'u']})

Parameter('EGFR_A_activation_RAF_0_2kc', KC)
Parameter('IGF1R_A_activation_RAF_0_2kc', KC)
Parameter('IGF1_ligand_receptor_binding_IGF1R_0_2kf', KF)
Parameter('IGF1_ligand_receptor_binding_IGF1R_0_1kr', KR)
Parameter('IGF1R_A_activation_PI3K_0_2kc', KC)
Parameter('EGFR_A_activation_PI3K_0_2kc', KC)
Parameter('AKT_p1_p1_phosphorylation_p70S6K_0_2kf', KF)
Parameter('AKT_p1_p1_phosphorylation_p70S6K_0_1kr', KR)
Parameter('AKT_p1_p1_phosphorylation_p70S6K_1_1kc', KC)
Parameter('ERK_p1_p1_phosphorylation_p70S6K_0_2kf', KF)
Parameter('ERK_p1_p1_phosphorylation_p70S6K_0_1kr', KR)
Parameter('ERK_p1_p1_phosphorylation_p70S6K_1_1kc', KC)
Parameter('TGFa_ligand_receptor_binding_EGFR_0_2kf', KF)
Parameter('TGFa_ligand_receptor_binding_EGFR_0_1kr', KR)
Parameter('AKT_p1_p1_phosphorylation_IRS1_0_2kf', KF)
Parameter('AKT_p1_p1_phosphorylation_IRS1_0_1kr', KR)
Parameter('AKT_p1_p1_phosphorylation_IRS1_1_1kc', KC)
Parameter('ERK_p1_p1_phosphorylation_IRS1_0_2kf', KF)
Parameter('ERK_p1_p1_phosphorylation_IRS1_0_1kr', KR)
Parameter('ERK_p1_p1_phosphorylation_IRS1_1_1kc', KC)
Parameter('RAF_A_p1_phosphorylation_MEK_0_2kf', KF)
Parameter('RAF_A_p1_phosphorylation_MEK_0_1kr', KR)
Parameter('RAF_A_p1_phosphorylation_MEK_1_1kc', KC)
Parameter('PI3K_A_p1_phosphorylation_AKT_0_2kf', KF)
Parameter('PI3K_A_p1_phosphorylation_AKT_0_1kr', KR)
Parameter('PI3K_A_p1_phosphorylation_AKT_1_1kc', KC)
Parameter('AKT_p1_p1_phosphorylation_GSK3_0_2kf', KF)
Parameter('AKT_p1_p1_phosphorylation_GSK3_0_1kr', KR)
Parameter('AKT_p1_p1_phosphorylation_GSK3_1_1kc', KC)
Parameter('ERK_p1_p1_phosphorylation_GSK3_0_2kf', KF)
Parameter('ERK_p1_p1_phosphorylation_GSK3_0_1kr', KR)
Parameter('ERK_p1_p1_phosphorylation_GSK3_1_1kc', KC)
Parameter('MEK_p1_p1_phosphorylation_ERK_0_2kf', KF)
Parameter('MEK_p1_p1_phosphorylation_ERK_0_1kr', KR)
Parameter('MEK_p1_p1_phosphorylation_ERK_1_1kc', KC)
Parameter('RAF_0_0', IC)
Parameter('RAF_1_0', IC)
Parameter('TGFa_0_0', IC)
Parameter('IGF1R_0_0', IC)
Parameter('IGF1R_1_0', IC)
Parameter('IGF1_0_0', IC)
Parameter('PI3K_0_0', IC)
Parameter('PI3K_1_0', IC)
Parameter('p70S6K_0_0', lp*343.5)
Parameter('p70S6K_1_0', lp*6000)
Parameter('EGFR_0_0', lp*75.5)
Parameter('EGFR_1_0', lp*1000)
Parameter('IRS1_0_0', lp*93)
Parameter('IRS1_1_0', lp*2000)
Parameter('MEK_0_0', lp*904)
Parameter('MEK_1_0', lp*8000)
Parameter('AKT_0_0', lp*143.5)
Parameter('AKT_1_0', lp*15000)
Parameter('GSK3_0_0', lp*265)
Parameter('GSK3_1_0', lp*3000)
Parameter('ERK_0_0', lp*361)
Parameter('ERK_1_0', lp*6000)

Observable('RAF_0_obs', RAF(state='I', MEK=None))
Observable('RAF_1_obs', RAF(state='I', MEK=ANY))
Observable('RAF_2_obs', RAF(state='A', MEK=None))
Observable('RAF_3_obs', RAF(state='A', MEK=ANY))
Observable('TGFa_0_obs', TGFa(EGFR=None))
Observable('TGFa_1_obs', TGFa(EGFR=ANY))
Observable('IGF1R_0_obs', IGF1R(state='A', IGF1=None))
Observable('IGF1R_1_obs', IGF1R(state='A', IGF1=ANY))
Observable('IGF1R_2_obs', IGF1R(state='I', IGF1=None))
Observable('IGF1R_3_obs', IGF1R(state='I', IGF1=ANY))
Observable('IGF1_0_obs', IGF1(IGF1R=None))
Observable('IGF1_1_obs', IGF1(IGF1R=ANY))
Observable('PI3K_0_obs', PI3K(state='I', AKT=None))
Observable('PI3K_1_obs', PI3K(state='I', AKT=ANY))
Observable('PI3K_2_obs', PI3K(state='A', AKT=None))
Observable('PI3K_3_obs', PI3K(state='A', AKT=ANY))
Observable('p70S6K_0_obs', p70S6K(AKT=None, p1_site='u', ERK=None))
Observable('p70S6K_1_obs', p70S6K(AKT=None, p1_site='u', ERK=ANY))
Observable('p70S6K_2_obs', p70S6K(AKT=None, p1_site='p', ERK=None))
Observable('p70S6K_3_obs', p70S6K(AKT=None, p1_site='p', ERK=ANY))
Observable('p70S6K_4_obs', p70S6K(AKT=ANY, p1_site='u', ERK=None))
Observable('p70S6K_5_obs', p70S6K(AKT=ANY, p1_site='u', ERK=ANY))
Observable('p70S6K_6_obs', p70S6K(AKT=ANY, p1_site='p', ERK=None))
Observable('p70S6K_7_obs', p70S6K(AKT=ANY, p1_site='p', ERK=ANY))
Observable('EGFR_0_obs', EGFR(state='A', TGFa=None))
Observable('EGFR_1_obs', EGFR(state='A', TGFa=ANY))
Observable('EGFR_2_obs', EGFR(state='I', TGFa=None))
Observable('EGFR_3_obs', EGFR(state='I', TGFa=ANY))
Observable('IRS1_0_obs', IRS1(AKT=None, p1_site='u', ERK=None))
Observable('IRS1_1_obs', IRS1(AKT=None, p1_site='u', ERK=ANY))
Observable('IRS1_2_obs', IRS1(AKT=None, p1_site='p', ERK=None))
Observable('IRS1_3_obs', IRS1(AKT=None, p1_site='p', ERK=ANY))
Observable('IRS1_4_obs', IRS1(AKT=ANY, p1_site='u', ERK=None))
Observable('IRS1_5_obs', IRS1(AKT=ANY, p1_site='u', ERK=ANY))
Observable('IRS1_6_obs', IRS1(AKT=ANY, p1_site='p', ERK=None))
Observable('IRS1_7_obs', IRS1(AKT=ANY, p1_site='p', ERK=ANY))
Observable('MEK_0_obs', MEK(RAF=None, p1_site='u', ERK=None))
Observable('MEK_1_obs', MEK(RAF=None, p1_site='u', ERK=ANY))
Observable('MEK_2_obs', MEK(RAF=None, p1_site='p', ERK=None))
Observable('MEK_3_obs', MEK(RAF=None, p1_site='p', ERK=ANY))
Observable('MEK_4_obs', MEK(RAF=ANY, p1_site='u', ERK=None))
Observable('MEK_5_obs', MEK(RAF=ANY, p1_site='u', ERK=ANY))
Observable('MEK_6_obs', MEK(RAF=ANY, p1_site='p', ERK=None))
Observable('MEK_7_obs', MEK(RAF=ANY, p1_site='p', ERK=ANY))
Observable('AKT_0_obs', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None))
Observable('AKT_1_obs', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=ANY))
Observable('AKT_2_obs', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=ANY, GSK3=None))
Observable('AKT_3_obs', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=ANY, GSK3=ANY))
Observable('AKT_4_obs', AKT(p1_site='p', p70S6K=None, IRS1=ANY, PI3K=None, GSK3=None))
Observable('AKT_5_obs', AKT(p1_site='p', p70S6K=None, IRS1=ANY, PI3K=None, GSK3=ANY))
Observable('AKT_6_obs', AKT(p1_site='p', p70S6K=None, IRS1=ANY, PI3K=ANY, GSK3=None))
Observable('AKT_7_obs', AKT(p1_site='p', p70S6K=None, IRS1=ANY, PI3K=ANY, GSK3=ANY))
Observable('AKT_8_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=None, PI3K=None, GSK3=None))
Observable('AKT_9_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=None, PI3K=None, GSK3=ANY))
Observable('AKT_10_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=None, PI3K=ANY, GSK3=None))
Observable('AKT_11_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=None, PI3K=ANY, GSK3=ANY))
Observable('AKT_12_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=ANY, PI3K=None, GSK3=None))
Observable('AKT_13_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=ANY, PI3K=None, GSK3=ANY))
Observable('AKT_14_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=ANY, PI3K=ANY, GSK3=None))
Observable('AKT_15_obs', AKT(p1_site='p', p70S6K=ANY, IRS1=ANY, PI3K=ANY, GSK3=ANY))
Observable('AKT_16_obs', AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=None, GSK3=None))
Observable('AKT_17_obs', AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=None, GSK3=ANY))
Observable('AKT_18_obs', AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=ANY, GSK3=None))
Observable('AKT_19_obs', AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=ANY, GSK3=ANY))
Observable('AKT_20_obs', AKT(p1_site='u', p70S6K=None, IRS1=ANY, PI3K=None, GSK3=None))
Observable('AKT_21_obs', AKT(p1_site='u', p70S6K=None, IRS1=ANY, PI3K=None, GSK3=ANY))
Observable('AKT_22_obs', AKT(p1_site='u', p70S6K=None, IRS1=ANY, PI3K=ANY, GSK3=None))
Observable('AKT_23_obs', AKT(p1_site='u', p70S6K=None, IRS1=ANY, PI3K=ANY, GSK3=ANY))
Observable('AKT_24_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=None, PI3K=None, GSK3=None))
Observable('AKT_25_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=None, PI3K=None, GSK3=ANY))
Observable('AKT_26_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=None, PI3K=ANY, GSK3=None))
Observable('AKT_27_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=None, PI3K=ANY, GSK3=ANY))
Observable('AKT_28_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=ANY, PI3K=None, GSK3=None))
Observable('AKT_29_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=ANY, PI3K=None, GSK3=ANY))
Observable('AKT_30_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=ANY, PI3K=ANY, GSK3=None))
Observable('AKT_31_obs', AKT(p1_site='u', p70S6K=ANY, IRS1=ANY, PI3K=ANY, GSK3=ANY))
Observable('GSK3_0_obs', GSK3(AKT=None, p1_site='u', ERK=None))
Observable('GSK3_1_obs', GSK3(AKT=None, p1_site='u', ERK=ANY))
Observable('GSK3_2_obs', GSK3(AKT=None, p1_site='p', ERK=None))
Observable('GSK3_3_obs', GSK3(AKT=None, p1_site='p', ERK=ANY))
Observable('GSK3_4_obs', GSK3(AKT=ANY, p1_site='u', ERK=None))
Observable('GSK3_5_obs', GSK3(AKT=ANY, p1_site='u', ERK=ANY))
Observable('GSK3_6_obs', GSK3(AKT=ANY, p1_site='p', ERK=None))
Observable('GSK3_7_obs', GSK3(AKT=ANY, p1_site='p', ERK=ANY))
Observable('ERK_0_obs', ERK(p1_site='p', p70S6K=None, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_1_obs', ERK(p1_site='p', p70S6K=None, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_2_obs', ERK(p1_site='p', p70S6K=None, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_3_obs', ERK(p1_site='p', p70S6K=None, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_4_obs', ERK(p1_site='p', p70S6K=None, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_5_obs', ERK(p1_site='p', p70S6K=None, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_6_obs', ERK(p1_site='p', p70S6K=None, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_7_obs', ERK(p1_site='p', p70S6K=None, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_8_obs', ERK(p1_site='p', p70S6K=ANY, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_9_obs', ERK(p1_site='p', p70S6K=ANY, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_10_obs', ERK(p1_site='p', p70S6K=ANY, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_11_obs', ERK(p1_site='p', p70S6K=ANY, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_12_obs', ERK(p1_site='p', p70S6K=ANY, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_13_obs', ERK(p1_site='p', p70S6K=ANY, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_14_obs', ERK(p1_site='p', p70S6K=ANY, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_15_obs', ERK(p1_site='p', p70S6K=ANY, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_16_obs', ERK(p1_site='u', p70S6K=None, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_17_obs', ERK(p1_site='u', p70S6K=None, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_18_obs', ERK(p1_site='u', p70S6K=None, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_19_obs', ERK(p1_site='u', p70S6K=None, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_20_obs', ERK(p1_site='u', p70S6K=None, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_21_obs', ERK(p1_site='u', p70S6K=None, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_22_obs', ERK(p1_site='u', p70S6K=None, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_23_obs', ERK(p1_site='u', p70S6K=None, IRS1=ANY, GSK3=ANY, MEK=ANY))
Observable('ERK_24_obs', ERK(p1_site='u', p70S6K=ANY, IRS1=None, GSK3=None, MEK=None))
Observable('ERK_25_obs', ERK(p1_site='u', p70S6K=ANY, IRS1=None, GSK3=None, MEK=ANY))
Observable('ERK_26_obs', ERK(p1_site='u', p70S6K=ANY, IRS1=None, GSK3=ANY, MEK=None))
Observable('ERK_27_obs', ERK(p1_site='u', p70S6K=ANY, IRS1=None, GSK3=ANY, MEK=ANY))
Observable('ERK_28_obs', ERK(p1_site='u', p70S6K=ANY, IRS1=ANY, GSK3=None, MEK=None))
Observable('ERK_29_obs', ERK(p1_site='u', p70S6K=ANY, IRS1=ANY, GSK3=None, MEK=ANY))
Observable('ERK_30_obs', ERK(p1_site='u', p70S6K=ANY, IRS1=ANY, GSK3=ANY, MEK=None))
Observable('ERK_31_obs', ERK(p1_site='u', p70S6K=ANY, IRS1=ANY, GSK3=ANY, MEK=ANY))

Rule('EGFR_A_activation_RAF_0', EGFR(state='A') + RAF(state='I') >> EGFR(state='A') + RAF(state='A'), EGFR_A_activation_RAF_0_2kc)
Rule('IGF1R_A_activation_RAF_0', IGF1R(state='A') + RAF(state='I') >> IGF1R(state='A') + RAF(state='A'), IGF1R_A_activation_RAF_0_2kc)
Rule('IGF1_ligand_receptor_binding_IGF1R_0', IGF1(IGF1R=None) + IGF1R(state='I', IGF1=None) <> IGF1(IGF1R=1) % IGF1R(state='A', IGF1=1), IGF1_ligand_receptor_binding_IGF1R_0_2kf, IGF1_ligand_receptor_binding_IGF1R_0_1kr)
Rule('IGF1R_A_activation_PI3K_0', IGF1R(state='A') + PI3K(state='I') >> IGF1R(state='A') + PI3K(state='A'), IGF1R_A_activation_PI3K_0_2kc)
Rule('EGFR_A_activation_PI3K_0', EGFR(state='A') + PI3K(state='I') >> EGFR(state='A') + PI3K(state='A'), EGFR_A_activation_PI3K_0_2kc)
Rule('AKT_p1_p1_phosphorylation_p70S6K_0', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) + p70S6K(AKT=None, p1_site='u', ERK=None) <> AKT(p1_site='p', p70S6K=1, IRS1=None, PI3K=None, GSK3=None) % p70S6K(AKT=1, p1_site='u', ERK=None), AKT_p1_p1_phosphorylation_p70S6K_0_2kf, AKT_p1_p1_phosphorylation_p70S6K_0_1kr)
Rule('AKT_p1_p1_phosphorylation_p70S6K_1', AKT(p1_site='p', p70S6K=1, IRS1=None, PI3K=None, GSK3=None) % p70S6K(AKT=1, p1_site='u', ERK=None) >> AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) + p70S6K(AKT=None, p1_site='p', ERK=None), AKT_p1_p1_phosphorylation_p70S6K_1_1kc)
Rule('ERK_p1_p1_phosphorylation_p70S6K_0', ERK(p1_site='p', p70S6K=None, IRS1=None, GSK3=None, MEK=None) + p70S6K(AKT=None, p1_site='u', ERK=None) <> ERK(p1_site='p', p70S6K=1, IRS1=None, GSK3=None, MEK=None) % p70S6K(AKT=None, p1_site='u', ERK=1), ERK_p1_p1_phosphorylation_p70S6K_0_2kf, ERK_p1_p1_phosphorylation_p70S6K_0_1kr)
Rule('ERK_p1_p1_phosphorylation_p70S6K_1', ERK(p1_site='p', p70S6K=1, IRS1=None, GSK3=None, MEK=None) % p70S6K(AKT=None, p1_site='u', ERK=1) >> ERK(p1_site='p', p70S6K=None, IRS1=None, GSK3=None, MEK=None) + p70S6K(AKT=None, p1_site='p', ERK=None), ERK_p1_p1_phosphorylation_p70S6K_1_1kc)
Rule('TGFa_ligand_receptor_binding_EGFR_0', TGFa(EGFR=None) + EGFR(state='I', TGFa=None) <> TGFa(EGFR=1) % EGFR(state='A', TGFa=1), TGFa_ligand_receptor_binding_EGFR_0_2kf, TGFa_ligand_receptor_binding_EGFR_0_1kr)
Rule('AKT_p1_p1_phosphorylation_IRS1_0', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) + IRS1(AKT=None, p1_site='u', ERK=None) <> AKT(p1_site='p', p70S6K=None, IRS1=1, PI3K=None, GSK3=None) % IRS1(AKT=1, p1_site='u', ERK=None), AKT_p1_p1_phosphorylation_IRS1_0_2kf, AKT_p1_p1_phosphorylation_IRS1_0_1kr)
Rule('AKT_p1_p1_phosphorylation_IRS1_1', AKT(p1_site='p', p70S6K=None, IRS1=1, PI3K=None, GSK3=None) % IRS1(AKT=1, p1_site='u', ERK=None) >> AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) + IRS1(AKT=None, p1_site='p', ERK=None), AKT_p1_p1_phosphorylation_IRS1_1_1kc)
Rule('ERK_p1_p1_phosphorylation_IRS1_0', ERK(p1_site='p', p70S6K=None, IRS1=None, GSK3=None, MEK=None) + IRS1(AKT=None, p1_site='u', ERK=None) <> ERK(p1_site='p', p70S6K=None, IRS1=1, GSK3=None, MEK=None) % IRS1(AKT=None, p1_site='u', ERK=1), ERK_p1_p1_phosphorylation_IRS1_0_2kf, ERK_p1_p1_phosphorylation_IRS1_0_1kr)
Rule('ERK_p1_p1_phosphorylation_IRS1_1', ERK(p1_site='p', p70S6K=None, IRS1=1, GSK3=None, MEK=None) % IRS1(AKT=None, p1_site='u', ERK=1) >> ERK(p1_site='p', p70S6K=None, IRS1=None, GSK3=None, MEK=None) + IRS1(AKT=None, p1_site='p', ERK=None), ERK_p1_p1_phosphorylation_IRS1_1_1kc)
Rule('RAF_A_p1_phosphorylation_MEK_0', RAF(state='A', MEK=None) + MEK(RAF=None, p1_site='u', ERK=None) <> RAF(state='A', MEK=1) % MEK(RAF=1, p1_site='u', ERK=None), RAF_A_p1_phosphorylation_MEK_0_2kf, RAF_A_p1_phosphorylation_MEK_0_1kr)
Rule('RAF_A_p1_phosphorylation_MEK_1', RAF(state='A', MEK=1) % MEK(RAF=1, p1_site='u', ERK=None) >> RAF(state='A', MEK=None) + MEK(RAF=None, p1_site='p', ERK=None), RAF_A_p1_phosphorylation_MEK_1_1kc)
Rule('PI3K_A_p1_phosphorylation_AKT_0', PI3K(state='A', AKT=None) + AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) <> PI3K(state='A', AKT=1) % AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=1, GSK3=None), PI3K_A_p1_phosphorylation_AKT_0_2kf, PI3K_A_p1_phosphorylation_AKT_0_1kr)
Rule('PI3K_A_p1_phosphorylation_AKT_1', PI3K(state='A', AKT=1) % AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=1, GSK3=None) >> PI3K(state='A', AKT=None) + AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None), PI3K_A_p1_phosphorylation_AKT_1_1kc)
Rule('AKT_p1_p1_phosphorylation_GSK3_0', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) + GSK3(AKT=None, p1_site='u', ERK=None) <> AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=1) % GSK3(AKT=1, p1_site='u', ERK=None), AKT_p1_p1_phosphorylation_GSK3_0_2kf, AKT_p1_p1_phosphorylation_GSK3_0_1kr)
Rule('AKT_p1_p1_phosphorylation_GSK3_1', AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=1) % GSK3(AKT=1, p1_site='u', ERK=None) >> AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None) + GSK3(AKT=None, p1_site='p', ERK=None), AKT_p1_p1_phosphorylation_GSK3_1_1kc)
Rule('ERK_p1_p1_phosphorylation_GSK3_0', ERK(p1_site='p', p70S6K=None, IRS1=None, GSK3=None, MEK=None) + GSK3(AKT=None, p1_site='u', ERK=None) <> ERK(p1_site='p', p70S6K=None, IRS1=None, GSK3=1, MEK=None) % GSK3(AKT=None, p1_site='u', ERK=1), ERK_p1_p1_phosphorylation_GSK3_0_2kf, ERK_p1_p1_phosphorylation_GSK3_0_1kr)
Rule('ERK_p1_p1_phosphorylation_GSK3_1', ERK(p1_site='p', p70S6K=None, IRS1=None, GSK3=1, MEK=None) % GSK3(AKT=None, p1_site='u', ERK=1) >> ERK(p1_site='p', p70S6K=None, IRS1=None, GSK3=None, MEK=None) + GSK3(AKT=None, p1_site='p', ERK=None), ERK_p1_p1_phosphorylation_GSK3_1_1kc)
Rule('MEK_p1_p1_phosphorylation_ERK_0', MEK(RAF=None, p1_site='p', ERK=None) + ERK(p1_site='u', p70S6K=None, IRS1=None, GSK3=None, MEK=None) <> MEK(RAF=None, p1_site='p', ERK=1) % ERK(p1_site='u', p70S6K=None, IRS1=None, GSK3=None, MEK=1), MEK_p1_p1_phosphorylation_ERK_0_2kf, MEK_p1_p1_phosphorylation_ERK_0_1kr)
Rule('MEK_p1_p1_phosphorylation_ERK_1', MEK(RAF=None, p1_site='p', ERK=1) % ERK(p1_site='u', p70S6K=None, IRS1=None, GSK3=None, MEK=1) >> MEK(RAF=None, p1_site='p', ERK=None) + ERK(p1_site='p', p70S6K=None, IRS1=None, GSK3=None, MEK=None), MEK_p1_p1_phosphorylation_ERK_1_1kc)

Initial(RAF(state='I', MEK=None), RAF_0_0)
Initial(RAF(state='A', MEK=None), RAF_1_0)
Initial(TGFa(EGFR=None), TGFa_0_0)
Initial(IGF1R(state='A', IGF1=None), IGF1R_0_0)
Initial(IGF1R(state='I', IGF1=None), IGF1R_1_0)
Initial(IGF1(IGF1R=None), IGF1_0_0)
Initial(PI3K(state='I', AKT=None), PI3K_0_0)
Initial(PI3K(state='A', AKT=None), PI3K_1_0)
Initial(p70S6K(AKT=None, p1_site='u', ERK=None), p70S6K_0_0)
Initial(p70S6K(AKT=None, p1_site='p', ERK=None), p70S6K_1_0)
Initial(EGFR(state='A', TGFa=None), EGFR_0_0)
Initial(EGFR(state='I', TGFa=None), EGFR_1_0)
Initial(IRS1(AKT=None, p1_site='u', ERK=None), IRS1_0_0)
Initial(IRS1(AKT=None, p1_site='p', ERK=None), IRS1_1_0)
Initial(MEK(RAF=None, p1_site='u', ERK=None), MEK_0_0)
Initial(MEK(RAF=None, p1_site='p', ERK=None), MEK_1_0)
Initial(AKT(p1_site='p', p70S6K=None, IRS1=None, PI3K=None, GSK3=None), AKT_0_0)
Initial(AKT(p1_site='u', p70S6K=None, IRS1=None, PI3K=None, GSK3=None), AKT_1_0)
Initial(GSK3(AKT=None, p1_site='u', ERK=None), GSK3_0_0)
Initial(GSK3(AKT=None, p1_site='p', ERK=None), GSK3_1_0)
Initial(ERK(p1_site='p', p70S6K=None, IRS1=None, GSK3=None, MEK=None), ERK_0_0)
Initial(ERK(p1_site='u', p70S6K=None, IRS1=None, GSK3=None, MEK=None), ERK_1_0)

# t = np.linspace(0,30, 1001)
# solve_mod = Solver(model, t)
# solve_mod.run()
#
# import matplotlib.pyplot as plt
#
# plt.plot(t, solve_mod.result.all['__s15'])