language: python
sudo: false
python:
- '2.7'
addons:
  apt:
    sources:
    - libgraphviz-dev
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh
    -O miniconda.sh
- chmod +x miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda install --yes -c conda-forge python="$TRAVIS_PYTHON_VERSION"
    numpy=1.13 scipy matplotlib seaborn sympy networkx nose h5py pexpect pandas pydot ipython scikit-learn coveralls
- pip install git+https://github.com/pysb/pysb.git
- pip install python-coveralls pathos hdbscan editdistance
- mkdir -p ~/.config/matplotlib
- echo "backend:Agg" > ~/.config/matplotlib/matplotlibrc
- conda install --yes -c alubbock bionetgen

install:
  python setup.py build --build-lib=build/lib
script:
  nosetests build/lib/tropical --with-coverage
  --cover-package=build/lib/tropical
after_success:
  coveralls

notifications:
  slack: lopezlab:mKQHRW1hyvJVLCX8ZWSgwhRY