lenguage: python
sudo: false
python:
- '2.7'
addons:
  apt:
    sources:
    -libgraphviz-dev
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda/bin:$PATH
- conda update --yes conda
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib sympy networkx
  nose h5py
- pip install -i https://pypi.binstar.org/pypi/simple pygraphviz
- pip install git+https://github.com/pysb/pysb.git
- pip install python-coveralls pathos
- wget "http://www.csb.pitt.edu/Faculty/Faeder/wp-content/uploads/2017/04/BioNetGen-2.2.6-stable_Linux.tar.gz"
    -O bionetgen.tar.gz
- tar xzf bionetgen.tar.gz
- export BNGPATH=`pwd`/BioNetGen-2.2.6-stable

install:
  python setup.py build --build-lib=build/lib
script:
  nosetests build/lib/tropical --with-coverage --cover-inclusive
after_success:
  coveralls