language: python
sudo: required
dist: trusty
env:
- PYVER=3.6
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda${PYVER:0:1}-latest-Linux-x86_64.sh
  -O miniconda.sh
- chmod +x miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda install --yes -c conda-forge python="$PYVER" numpy scipy matplotlib sympy
  pytest h5py pandas scikit-learn coveralls cython editdistance pathos hdbscan networkx
  pydot coverage
- conda install --yes -c alubbock pysb
- if [[ $PYVER == 2.7 ]]; then conda update --yes numpy; fi
- pip install anytree
- mkdir -p ~/.config/matplotlib
- echo "backend:Agg" > ~/.config/matplotlib/matplotlibrc
install: python setup.py build --build-lib=build/lib
script:
  |
  coverage run -m pytest --pyargs pydyno
  coverage report -m
after_success: coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: ortega2247
  password:
    secure: a5IJr3aDCwQRpKdwQ8+XyXZjpSZLjWDWPw7EYwqKVcouLDAIiJPK4XYhC5Qr9oEdWeMnWffiD1tszfH0I3VNGBV/QBAwwqQNDn9GtfYCWzTCz0KlHJaPIQYFMyVtD8d9EQbm2bf05VFgND2jEDq0CS1XrwkusbV+V3YuCfIJF8p7hRz/As58JeJSjE9dliTWexIpSNfjIb0exGo2nf3pj6nHzRkpIKtbSolzv9kf/0/O/wBI5lqCiYy1mgxmfQyGzsgRMssr5fUhKXBEAWYOLapfJHdg8Apc+DMmaHCG98xskCvXvBBMZwAoEbiPrQ28MXxtP8UsWMmNolDDX9waD1HpxW/eYclo35nSDfX4MAm6+U5lq6eyUTcS9xOEnYKpitjoFRjwfW1Hi9sjMKRod1JiuiWn6Nz0XMowrNygLpqtO+B90vVCa9W5uNsQqyw18T97xCz4kdtuxc1Niw1ztjk0XRgpLpLuvYmZV0JY/QjbYG1shbKmcTRw49S1CVQ7HO6G59OciBc/OselaFhO/OKrfXK+5uHFWY7HA7tna0L8OcZm7oza60WgZXXvaIrpCR0QxKm91S497mZSlsWFSmKlGvSXutEQ1wNxpsbc2nydtyUgoCcKQVrXLh/JFzf7qRTugGmN4hc+YVimG4dfFt9ykcPM04UZGRFhTYkOmMs=
  on:
    tags: true
notifications:
  slack: lopezlab:mKQHRW1hyvJVLCX8ZWSgwhRY
